name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Dependencies
      run: sudo apt-get install cmake libc-ares-dev libcurl4-openssl-dev libev-dev build-essential clang clang-tidy

    - name: Configure CMake
      env:
        CC: ${{ matrix.compiler }}
      run: cmake -B ${{github.workspace}}/

    - name: Build
      env:
        CC: ${{ matrix.compiler }}
      # Build your program with the given configuration
      run: make -C ${{github.workspace}}/
